/**
 * Stock photography manifest (generated by the image pipeline; edit alt text freely).
 * All files live in /public/images/stock and are licensed under the Pexels License
 * (free for commercial use, no attribution required). Sources: public/images/stock/CREDITS.md
 *
 * RULE: these are ambience photos. Never present them as customers, never attach
 * invented quotes or names to them.
 */
export const IMG = {
  "agent-finance": { src: "/images/stock/agent-finance.jpg", w: 2000, h: 1333, alt: "Finance professional working with invoices on a laptop and calculator" },
  "agent-marketing": { src: "/images/stock/agent-marketing.jpg", w: 2000, h: 1322, alt: "Team planning a campaign around a laptop and chart board" },
  "agent-voice": { src: "/images/stock/agent-voice.jpg", w: 2000, h: 3000, alt: "Smiling business professional on a phone call" },
  "arch-follow": { src: "/images/stock/arch-follow.jpg", w: 2000, h: 1333, alt: "Woman working on a laptop and taking notes in a café" },
  "arch-insight": { src: "/images/stock/arch-insight.jpg", w: 2000, h: 1333, alt: "Man reviewing business charts on a laptop" },
  "arch-reply": { src: "/images/stock/arch-reply.jpg", w: 2000, h: 1333, alt: "Smiling customer service representative wearing a headset" },
  "cta": { src: "/images/stock/cta.jpg", w: 2000, h: 1500, alt: "City skyline at sunset" },
  "engineering": { src: "/images/stock/engineering.jpg", w: 2000, h: 1333, alt: "Software team working together in an open-plan office" },
  "hero-circle": { src: "/images/stock/hero-circle.jpg", w: 2000, h: 3000, alt: "Smiling shopkeeper in his store" },
  "hero-main": { src: "/images/stock/hero-main.jpg", w: 2000, h: 1333, alt: "Florist in an apron talking on her phone in her flower shop" },
  "ind-ecommerce": { src: "/images/stock/ind-ecommerce.jpg", w: 2000, h: 1333, alt: "Woman packing clothes for online orders" },
  "ind-education": { src: "/images/stock/ind-education.jpg", w: 2000, h: 1333, alt: "Students working on laptops in a bright classroom" },
  "ind-energy": { src: "/images/stock/ind-energy.jpg", w: 2000, h: 1333, alt: "Engineer and site manager in hard hats beside solar panels" },
  "ind-enterprise": { src: "/images/stock/ind-enterprise.jpg", w: 2000, h: 1328, alt: "Glass office tower reflecting the sky" },
  "ind-fintech": { src: "/images/stock/ind-fintech.jpg", w: 2000, h: 3000, alt: "Man using a smartphone and a payment card" },
  "ind-healthcare": { src: "/images/stock/ind-healthcare.jpg", w: 2000, h: 1333, alt: "Doctor reviewing information on a tablet" },
  "ind-logistics": { src: "/images/stock/ind-logistics.jpg", w: 2000, h: 1333, alt: "Warehouse team standing among shelves of inventory" },
  "ind-manufacturing": { src: "/images/stock/ind-manufacturing.jpg", w: 2000, h: 1333, alt: "Factory worker smiling beside industrial machinery" },
  "ind-saas": { src: "/images/stock/ind-saas.jpg", w: 2000, h: 1333, alt: "Hands coding on a laptop" },
  "ind-startup": { src: "/images/stock/ind-startup.jpg", w: 2000, h: 1125, alt: "Team meeting around a whiteboard presentation" },
  "mission": { src: "/images/stock/mission.jpg", w: 2000, h: 1333, alt: "Colleagues talking beside a window overlooking the city" },
  "prod-crm": { src: "/images/stock/prod-crm.jpg", w: 2000, h: 1333, alt: "Three colleagues collaborating around a laptop in a bright office" },
  "prod-hrm": { src: "/images/stock/prod-hrm.jpg", w: 2000, h: 1125, alt: "Professionals discussing strategy at an office" },
  "prod-instagram": { src: "/images/stock/prod-instagram.jpg", w: 2000, h: 3000, alt: "Woman photographing products for her small business with her phone" },
  "prod-whatsapp": { src: "/images/stock/prod-whatsapp.jpg", w: 2000, h: 1333, alt: "Woman checking messages on her phone in a café" },
  "story-crm": { src: "/images/stock/story-crm.jpg", w: 2000, h: 3000, alt: "Three young professionals collaborating at a high table" },
  "story-hrm": { src: "/images/stock/story-hrm.jpg", w: 2000, h: 1125, alt: "Manager interviewing a candidate in a modern office" },
  "story-instagram": { src: "/images/stock/story-instagram.jpg", w: 2000, h: 1333, alt: "Woman photographing clothes in a boutique" },
  "story-whatsapp": { src: "/images/stock/story-whatsapp.jpg", w: 2000, h: 3000, alt: "Woman relaxing on a sofa, reading messages on her phone" },
  "values": { src: "/images/stock/values.jpg", w: 2000, h: 1335, alt: "Colleagues sharing ideas in a bright open office" },
};

/** Props for next/image in `fill` mode. Usage: <Image {...fill("hero-main")} sizes="..." /> */
export function fill(key, position) {
  const i = IMG[key];
  if (!i) throw new Error("Unknown image key: " + key);
  return { src: i.src, alt: i.alt, fill: true, style: position ? { objectFit: "cover", objectPosition: position } : { objectFit: "cover" } };
}

/** Props for next/image with intrinsic size (keeps aspect ratio). */
export function sized(key) {
  const i = IMG[key];
  if (!i) throw new Error("Unknown image key: " + key);
  return { src: i.src, alt: i.alt, width: i.w, height: i.h };
}
